[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  identifier = "about"
  pageRef = "/about/vision-goals/"
  weight = 20

[[main]]
  name = "Vision & Goals"
  pageRef = "/about/vision-goals/"
  parent = "about"
  weight = 20

[[main]]
  name = "Current work"
  pageRef = "/work/"
  parent = "about"
  weight = 21

[[main]]
  name = "Open science"
  pageRef = "/open-science/"
  parent = "about"
  weight = 22

[[main]]
  name = "Publications"
  pageRef = "/publications/"
  parent = "about"
  weight = 23

[[main]]
  name = "Network"
  identifier = "network"
  pageRef = "/network/"
  weight = 30

[[main]]
  name = "Overview"
  pageRef = "/network/"
  parent = "network"
  weight = 30

[[main]]
  name = "Gardens"
  pageRef = "/gardens/"
  parent = "network"
  weight = 31

[[main]]
  name = "Research Laboratories"
  pageRef = "/labs/"
  parent = "network"
  weight = 32

[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 50
  [main.params]
    button = true

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/digital-botanical-gardens-initiative"
  weight = 10

[[social]]
  name = "Open notes"
  pre = "fas book-open"
  url = "https://www.dbgi.org/dendron-dbgi/"
  weight = 30
