[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 20

[[main]]
  name = "Contributors"
  pageRef = "/team/"
  weight = 30

[[main]]
  name = "Governance"
  pageRef = "/governance/"
  weight = 32

[[main]]
  name = "Labs"
  pageRef = "/labs/"
  weight = 33

[[main]]
  name = "Gardens"
  pageRef = "/gardens/"
  weight = 35

[[main]]
  name = "Observation"
  pageRef = "/observation-of-the-day/"
  weight = 37

[[main]]
  name = "Work"
  pageRef = "/work/"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 50

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/digital-botanical-gardens-initiative"
  weight = 10

[[social]]
  name = "Email"
  pre = "fas envelope"
  url = "mailto:dbgi@protonmail.ch"
  weight = 20

[[social]]
  name = "Open notes"
  pre = "fas book-open"
  url = "https://www.dbgi.org/dendron-dbgi/"
  weight = 30
